import type { PortfolioData } from "./types"

/**
 * The hardcoded content — today's single source of truth.
 *
 * Everything a visitor reads is in this file. No component imports it directly;
 * they all read it through usePortfolio(). When the admin API lands, this file
 * becomes the offline fallback and nothing else changes.
 *
 * TODO(ray): the values marked NEEDS-REAL-VALUE below are placeholders.
 */
export const defaultPortfolio: PortfolioData = {
  site: {
    siteName: "Raybean",
    pageTitle: "Raybean — Graphic Designer & Illustrator",
    metaDescription:
      "Raybean (Ray) — graphic designer, illustrator and video editor. Portfolio of graphic design, illustration, video and osu! storyboard work.",
    // NEEDS-REAL-VALUE: drop the PDF into public/ and this link works.
    resumeUrl: "/raybean-resume.pdf",
    resumeLabel: "click me for my resume!",
  },

  // No "home" entry — the Raybean logo is the link home, as in the reference.
  nav: [
    { id: "graphic-design", label: "graphic design", to: "/graphic-design" },
    { id: "illustration", label: "illustration", to: "/illustration" },
    { id: "video", label: "videos & storyboards", to: "/video" },
    { id: "commissions", label: "commissions", to: "/commissions" },
  ],

  socials: [
    {
      platform: "discord",
      label: "Discord",
      handle: "raybeanosu",
      // No public profile URL — this opens the contact modal instead.
      icon: "discord",
      color: "#5865F2", // Discord blurple
      showInHero: true,
      showInFooter: true,
      showInContact: false,
    },
    {
      platform: "email",
      label: "Email",
      handle: "raybeanosutourney@gmail.com",
      url: "mailto:raybeanosutourney@gmail.com",
      icon: "EnvelopeSimple",
      color: "#C08A2E", // no brand colour exists; warm gold ties into the palette
      showInHero: true,
      showInFooter: true,
      showInContact: false,
    },
    {
      platform: "twitter",
      label: "Twitter",
      handle: "raybeanosu",
      url: "https://twitter.com/raybeanosu",
      icon: "TwitterLogo",
      color: "#1DA1F2", // Twitter blue
      showInHero: true,
      showInFooter: true,
      showInContact: true,
    },
    {
      platform: "bluesky",
      label: "Bluesky",
      handle: "raybean.cc",
      url: "https://bsky.app/profile/raybean.cc",
      icon: "bluesky",
      color: "#0085FF", // Bluesky blue
      showInHero: true,
      showInFooter: true,
      showInContact: true,
    },
    {
      platform: "pixiv",
      label: "Pixiv",
      url: "https://www.pixiv.net/en/users/103389894",
      icon: "pixiv",
      color: "#0096FA", // Pixiv blue
      showInHero: true,
      showInFooter: true,
      showInContact: true,
    },
    {
      platform: "youtube",
      label: "YouTube",
      handle: "@raybeanosu",
      url: "https://www.youtube.com/@raybeanosu",
      icon: "YoutubeLogo",
      color: "#E62117", // YouTube red
      showInHero: true,
      showInFooter: true,
      showInContact: true,
    },
    {
      platform: "vgen",
      label: "VGen",
      // NEEDS-REAL-VALUE: no VGen URL supplied yet, so it is hidden everywhere.
      // Add the url and flip these flags to show it.
      icon: "vgen",
      color: "#F05A28", // VGen orange
      showInHero: false,
      showInFooter: false,
      showInContact: false,
    },
  ],

  home: {
    hero: {
      greeting: "Hello, I'm Raybean!",
      intro: [
        "You can call me **Ray**.\nI'm a **graphic designer and illustrator**. I also like making **videos** from time to time. I love making cute things! >w<",
        "You can contact me via **discord** or **email**. I hope to be working with you in the future, making wonderful things together!~",
      ],
      // Ray's chibi, resized to 1000px and WebP'd (110KB, alpha intact) from the
      // 4.5MB source. If it ever fails to load, the placeholder circle renders.
      image: "/raybean-avatar.webp",
      imageAlt: "Chibi illustration of Raybean",
      imageCredit: {
        text: "Profile Photo by Dreamxiety!",
        note: "thank you!",
        href: "https://osu.ppy.sh/users/13103233",
      },
      ctaButtons: [
        {
          id: "resume",
          label: "my resume",
          href: "/raybean-resume.pdf",
          icon: "resume",
          external: true,
        },
        {
          id: "osu-profile",
          label: "my osu! profile",
          // NEEDS-REAL-VALUE: confirm the osu! username.
          href: "https://osu.ppy.sh/users/Raybean",
          icon: "osu",
          external: true,
        },
      ],
    },
    featured: {
      title: "Featured Works",
      description:
        "Some of my favourite projects! A combination of art, graphic design and osu! storyboards.",
    },
  },

  disciplines: [
    {
      id: "graphic-design",
      route: "/graphic-design",
      navLabel: "graphic design",
      section: { title: "graphic design" },
      toolsNote:
        "I mainly use **Adobe Photoshop, Figma and Affinity** for graphic designing, unless mentioned otherwise.",
      groups: [
        {
          id: "osu-projects",
          section: {
            title: "osu! projects",
            description:
              "I am a part of the osu! World Cup Design Team, responsible for creating the visuals for all osu! originals featured in World Cups.",
          },
          layout: "carousel",
        },
        {
          id: "community-projects",
          section: {
            title: "community projects",
            description:
              "These are some of the projects I've worked on for various osu! tournaments outside the World Cups. This was how I got my foot in the door with graphic design, back in 2023!",
          },
          layout: "carousel",
        },
        {
          id: "miscellaneous",
          section: {
            title: "miscellaneous",
            // TODO(ray): this line is my best read of the mock, which was too
            // small to be sure of. Correct it.
            description:
              "I have also worked on other projects, mostly in social media and merchandise design.",
          },
          layout: "carousel",
        },
      ],
    },
    {
      id: "illustration",
      route: "/illustration",
      navLabel: "illustration",
      section: {
        title: "illustration",
        description: "A small collection of my best works!",
      },
      // One group, no heading of its own — the page description covers it.
      groups: [{ id: "best-works", section: { title: "" }, layout: "masonry" }],
    },
    {
      id: "video",
      route: "/video",
      navLabel: "videos & storyboards",
      section: { title: "videos & storyboards" },
      groups: [
        {
          id: "videos",
          section: {
            title: "Videos",
            description:
              "I use DaVinci Resolve and occasionally Adobe After Effects for my videos.",
          },
          layout: "video-grid",
        },
        {
          id: "storyboards",
          section: {
            title: "osu! storyboards",
            description:
              "These are made not with a video editor, but directly inside osu!. These are some of my more recent works!",
          },
          layout: "video-grid",
        },
      ],
    },
  ],

  /*
   * The full catalog. Illustration titles are read from filenames and need
   * Ray's confirmation. Video and storyboard posters are the YouTube thumbnails,
   * pulled local; the cards open the embed. `image` is just a URL string, so it
   * becomes a CDN URL later with no code change.
   */
  works: [
    {
      id: "graphic-design-osu-projects-foxglove-1",
      artist: "Xyris",
      title: "FOXGLOVE",
      tags: ["osu! World Cup"],
      discipline: "graphic-design",
      group: "osu-projects",
      medium: "image",
      image: "/portfolio/gfx/osu-designs/foxglove.webp",
      width: 1600,
      height: 900,
      alt: "FOXGLOVE",
      featured: true,
      sortOrder: 1,
    },
    {
      id: "graphic-design-osu-projects-cansolbg-2",
      artist: "Cansol",
      title: "Out of Place",
      tags: ["osu! World Cup"],
      discipline: "graphic-design",
      group: "osu-projects",
      medium: "image",
      image: "/portfolio/gfx/osu-designs/cansolbg.webp",
      width: 1600,
      height: 900,
      alt: "Out of Place",
      featured: false,
      sortOrder: 2,
    },
    {
      id: "graphic-design-osu-projects-vacant-rhapsody-1-3",
      artist: "Penoreri",
      title: "Vacant Rhapsody",
      tags: ["osu! World Cup"],
      discipline: "graphic-design",
      group: "osu-projects",
      medium: "image",
      image: "/portfolio/gfx/osu-designs/vacant-rhapsody-1.webp",
      width: 1600,
      height: 900,
      alt: "Vacant Rhapsody",
      featured: true,
      sortOrder: 3,
    },
    {
      id: "graphic-design-osu-projects-vacant-rhapsody-2-4",
      artist: "Penoreri",
      title: "Vacant Rhapsody",
      tags: ["osu! World Cup"],
      discipline: "graphic-design",
      group: "osu-projects",
      medium: "image",
      image: "/portfolio/gfx/osu-designs/vacant-rhapsody-2.webp",
      width: 1600,
      height: 900,
      alt: "Vacant Rhapsody",
      featured: false,
      sortOrder: 4,
    },
    {
      id: "graphic-design-community-projects-1-5",
      title: "Australia & New Zealand Suiji",
      tags: ["Tournament"],
      discipline: "graphic-design",
      group: "community-projects",
      medium: "image",
      image: "/portfolio/gfx/community/1.webp",
      width: 500,
      height: 500,
      alt: "Australia & New Zealand Suiji",
      featured: false,
      sortOrder: 5,
    },
    {
      id: "graphic-design-community-projects-anomaly-maria-6",
      artist: "Kuro ft. Kasane Teto SV",
      title: "Anomaly Maria",
      tags: ["Tournament"],
      discipline: "graphic-design",
      group: "community-projects",
      medium: "image",
      image: "/portfolio/gfx/community/anomaly-maria.webp",
      width: 1600,
      height: 900,
      alt: "Anomaly Maria",
      featured: true,
      sortOrder: 6,
    },
    {
      id: "graphic-design-community-projects-coe-social-media-7",
      title: "cavoe's osu! event",
      tags: ["Social Media"],
      discipline: "graphic-design",
      group: "community-projects",
      medium: "image",
      image: "/portfolio/gfx/community/coe-social-media.webp",
      width: 1080,
      height: 1350,
      alt: "cavoe's osu! event",
      featured: false,
      sortOrder: 7,
    },
    {
      id: "graphic-design-community-projects-forum-banner1-8",
      title: "Fruit Loops Tournament 4",
      tags: ["Tournament"],
      discipline: "graphic-design",
      group: "community-projects",
      medium: "image",
      image: "/portfolio/gfx/community/forum-banner1.webp",
      width: 1600,
      height: 500,
      alt: "Fruit Loops Tournament 4",
      featured: false,
      sortOrder: 8,
    },
    {
      id: "graphic-design-community-projects-nacs-9",
      title: "North America Continental Summit",
      tags: ["Tournament"],
      discipline: "graphic-design",
      group: "community-projects",
      medium: "image",
      image: "/portfolio/gfx/community/nacs.webp",
      width: 1080,
      height: 300,
      alt: "North America Continental Summit",
      featured: false,
      sortOrder: 9,
    },
    {
      id: "graphic-design-community-projects-ocbs-10",
      title: "osu! Chennai Beachside Showdown",
      tags: ["Tournament"],
      discipline: "graphic-design",
      group: "community-projects",
      medium: "image",
      image: "/portfolio/gfx/community/ocbs.webp",
      width: 1400,
      height: 400,
      alt: "osu! Chennai Beachside Showdown",
      featured: false,
      sortOrder: 10,
    },
    {
      id: "graphic-design-community-projects-fruit-loops-3",
      title: "Fruit Loops Tournament 3",
      tags: ["Tournament"],
      discipline: "graphic-design",
      group: "community-projects",
      medium: "image",
      image: "/portfolio/gfx/community/2.webp",
      width: 1400,
      height: 500,
      alt: "Fruit Loops Tournament 3",
      featured: false,
      sortOrder: 11,
    },
    {
      id: "graphic-design-community-projects-in-sight",
      artist: "Krasper2",
      title: "In Sight",
      tags: ["Tournament"],
      discipline: "graphic-design",
      group: "community-projects",
      medium: "image",
      image: "/portfolio/gfx/community/cico.webp",
      width: 1600,
      height: 1600,
      alt: "Krasper2 - In Sight",
      featured: false,
      sortOrder: 12,
    },
    {
      id: "graphic-design-community-projects-osu-voice-2",
      title: "osu! voice 2",
      tags: ["Tournament"],
      discipline: "graphic-design",
      group: "community-projects",
      medium: "image",
      image: "/portfolio/gfx/community/osu-voice-2.webp",
      width: 1400,
      height: 400,
      alt: "osu! voice 2 banner",
      featured: false,
      sortOrder: 13,
    },
    {
      id: "graphic-design-miscellaneous-6wc4-india-thumbnail-wip-11",
      title: "6WC4 India",
      tags: ["YT Thumbnail"],
      discipline: "graphic-design",
      group: "miscellaneous",
      medium: "image",
      image: "/portfolio/gfx/misc/6wc4-india-thumbnail-wip.webp",
      width: 1600,
      height: 900,
      alt: "6WC4 India",
      featured: false,
      sortOrder: 11,
    },
    {
      id: "graphic-design-miscellaneous-coe-hoodie-12",
      title: "cavoe's osu! event 2026",
      tags: ["Merch"],
      discipline: "graphic-design",
      group: "miscellaneous",
      medium: "image",
      image: "/portfolio/gfx/misc/coe-hoodie.webp",
      width: 1600,
      height: 1200,
      alt: "cavoe's osu! event 2026",
      featured: false,
      sortOrder: 12,
    },
    {
      id: "graphic-design-miscellaneous-coe-shorts-13",
      title: "cavoe's osu! event 2026",
      tags: ["Merch"],
      discipline: "graphic-design",
      group: "miscellaneous",
      medium: "image",
      image: "/portfolio/gfx/misc/coe-shorts.webp",
      width: 942,
      height: 1180,
      alt: "cavoe's osu! event 2026",
      featured: false,
      sortOrder: 13,
    },
    {
      id: "graphic-design-miscellaneous-dj-mag-14",
      title: "DJ Mag",
      tags: ["YT Thumbnail"],
      discipline: "graphic-design",
      group: "miscellaneous",
      medium: "image",
      image: "/portfolio/gfx/misc/dj-mag.webp",
      width: 1600,
      height: 900,
      alt: "DJ Mag",
      featured: false,
      sortOrder: 14,
    },
    {
      id: "graphic-design-miscellaneous-hitsmun-24-branding-15",
      title: "HITS' Model United Nations 2024",
      tags: ["Branding"],
      discipline: "graphic-design",
      group: "miscellaneous",
      medium: "image",
      image: "/portfolio/gfx/misc/hitsmun-24-branding.webp",
      width: 1600,
      height: 900,
      alt: "HITS' Model United Nations 2024",
      featured: false,
      sortOrder: 15,
    },
    {
      id: "graphic-design-miscellaneous-hitsmun-social-1-16",
      title: "HITSMUN 2023",
      tags: ["Social Media"],
      discipline: "graphic-design",
      group: "miscellaneous",
      medium: "image",
      image: "/portfolio/gfx/misc/hitsmun-social-1.webp",
      width: 1600,
      height: 534,
      alt: "HITSMUN 2023",
      featured: false,
      sortOrder: 16,
    },
    {
      id: "graphic-design-miscellaneous-hitsmun-social-2-17",
      title: "HITSMUN 2023",
      tags: ["Social Media"],
      discipline: "graphic-design",
      group: "miscellaneous",
      medium: "image",
      image: "/portfolio/gfx/misc/hitsmun-social-2.webp",
      width: 1080,
      height: 1080,
      alt: "HITSMUN 2023",
      featured: false,
      sortOrder: 17,
    },
    {
      id: "graphic-design-miscellaneous-lld1-18",
      title: "LaborLess Digital",
      tags: ["Social Media"],
      discipline: "graphic-design",
      group: "miscellaneous",
      medium: "image",
      image: "/portfolio/gfx/misc/lld1.webp",
      width: 1280,
      height: 1600,
      alt: "LaborLess Digital",
      featured: false,
      sortOrder: 18,
    },
    {
      id: "graphic-design-miscellaneous-lld2-19",
      title: "LaborLess Digital",
      tags: ["Social Media"],
      discipline: "graphic-design",
      group: "miscellaneous",
      medium: "image",
      image: "/portfolio/gfx/misc/lld2.webp",
      width: 1200,
      height: 1600,
      alt: "LaborLess Digital",
      featured: false,
      sortOrder: 19,
    },
    {
      id: "graphic-design-miscellaneous-lld3-20",
      title: "LaborLess Digital",
      tags: ["Social Media"],
      discipline: "graphic-design",
      group: "miscellaneous",
      medium: "image",
      image: "/portfolio/gfx/misc/lld3.webp",
      width: 1200,
      height: 1600,
      alt: "LaborLess Digital",
      featured: false,
      sortOrder: 20,
    },
    {
      id: "graphic-design-miscellaneous-owc-yt-thumbnail-21",
      title: "osu! World Cup",
      tags: ["YT Thumbnail"],
      discipline: "graphic-design",
      group: "miscellaneous",
      medium: "image",
      image: "/portfolio/gfx/misc/owc-yt-thumbnail.webp",
      width: 1600,
      height: 900,
      alt: "osu! World Cup",
      featured: false,
      sortOrder: 21,
    },
    {
      id: "graphic-design-miscellaneous-lld4",
      title: "LaborLess Digital",
      tags: ["Social Media"],
      discipline: "graphic-design",
      group: "miscellaneous",
      medium: "image",
      image: "/portfolio/gfx/misc/lld4.webp",
      width: 1600,
      height: 1600,
      alt: "Mock social media post for LaborLess Digital",
      featured: false,
      sortOrder: 22,
    },
    {
      id: "graphic-design-miscellaneous-ocbs-id",
      title: "osu! Chennai Beachside Showdown",
      tags: ["ID Card"],
      discipline: "graphic-design",
      group: "miscellaneous",
      medium: "image",
      image: "/portfolio/gfx/misc/ocbs-id.webp",
      width: 1600,
      height: 1200,
      alt: "ID card design for osu! Chennai Beachside Showdown",
      featured: false,
      sortOrder: 23,
    },
    {
      id: "graphic-design-miscellaneous-lowola",
      title: "Lowola",
      tags: ["Vtuber Logo"],
      discipline: "graphic-design",
      group: "miscellaneous",
      medium: "image",
      image: "/portfolio/gfx/misc/lowola.webp",
      width: 500,
      height: 500,
      alt: "Vtuber-style logo for Lowola",
      featured: false,
      sortOrder: 24,
    },
    {
      id: "graphic-design-miscellaneous-utiba",
      title: "Utiba",
      tags: ["Vtuber Logo"],
      discipline: "graphic-design",
      group: "miscellaneous",
      medium: "image",
      image: "/portfolio/gfx/misc/utiba.webp",
      width: 576,
      height: 432,
      alt: "Vtuber-style logo for Utiba",
      featured: false,
      sortOrder: 25,
    },
    {
      id: "illustration-best-works-astrogirl-22",
      title: "Astro Girl",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/astrogirl.webp",
      width: 1600,
      height: 900,
      alt: "Astro Girl",
      featured: false,
      sortOrder: 22,
    },
    {
      id: "illustration-best-works-ayu-chloe-2-23",
      title: "Ayu & Chloe",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/ayu-chloe-2.webp",
      width: 1600,
      height: 900,
      alt: "Ayu & Chloe",
      featured: false,
      sortOrder: 23,
    },
    {
      id: "illustration-best-works-bocchi-24",
      title: "Bocchi",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/bocchi.webp",
      width: 1440,
      height: 1440,
      alt: "Bocchi",
      featured: false,
      sortOrder: 24,
    },
    {
      id: "illustration-best-works-capy1-25",
      title: "Capy",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/capy1.webp",
      width: 1000,
      height: 1000,
      alt: "Capy",
      featured: false,
      sortOrder: 25,
    },
    {
      id: "illustration-best-works-capy2-26",
      title: "Capy",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/capy2.webp",
      width: 1000,
      height: 1000,
      alt: "Capy",
      featured: false,
      sortOrder: 26,
    },
    {
      id: "illustration-best-works-fallen-27",
      title: "Wanderer of the Warm Winds",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/fallen.webp",
      width: 1081,
      height: 1600,
      alt: "Wanderer of the Warm Winds",
      featured: false,
      sortOrder: 27,
    },
    {
      id: "illustration-best-works-lucine-likes-bread-28",
      title: "Lucine Likes Bread",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/lucine-likes-bread.webp",
      width: 1440,
      height: 1440,
      alt: "Lucine Likes Bread",
      featured: false,
      sortOrder: 28,
    },
    {
      id: "illustration-best-works-maomao-29",
      title: "Maomao",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/maomao.webp",
      width: 1081,
      height: 1600,
      alt: "Maomao",
      featured: false,
      sortOrder: 29,
    },
    {
      id: "illustration-best-works-monitoring-30",
      artist: "DECO*27",
      title: "Monitoring",
      tags: ["Fanart"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/monitoring.webp",
      width: 1600,
      height: 900,
      alt: "Monitoring",
      featured: true,
      sortOrder: 30,
    },
    {
      id: "illustration-best-works-pippi-pencil-31",
      title: "Pippi",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/pippi-pencil.webp",
      width: 1129,
      height: 997,
      alt: "Pippi",
      featured: false,
      sortOrder: 31,
    },
    {
      id: "illustration-best-works-resonance-of-ice-stalactites-not-final-32",
      title: "Resonance of Ice Stalactites",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image:
        "/portfolio/illustrations/resonance-of-ice-stalactites-not-final.webp",
      alt: "Resonance of Ice Stalactites",
      featured: false,
      sortOrder: 32,
    },
    {
      id: "illustration-best-works-retry-now-33",
      title: "Retry Now",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/retry-now.webp",
      width: 1440,
      height: 1440,
      alt: "Retry Now",
      featured: false,
      sortOrder: 33,
    },
    {
      id: "illustration-best-works-rioxiety-yuri-34",
      title: "Rioxiety",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/rioxiety-yuri.webp",
      width: 1440,
      height: 1440,
      alt: "Rioxiety",
      featured: false,
      sortOrder: 34,
    },
    {
      id: "illustration-best-works-self-portrait-2024-35",
      title: "Self Portrait 2024",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/self-portrait-2024.webp",
      width: 1600,
      height: 900,
      alt: "Self Portrait 2024",
      featured: false,
      sortOrder: 35,
    },
    {
      id: "illustration-best-works-tatsuma-36",
      title: "Tatsuma",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/tatsuma.webp",
      width: 1440,
      height: 1440,
      alt: "Tatsuma",
      featured: false,
      sortOrder: 36,
    },
    {
      id: "illustration-best-works-vanda-the-outsider-37",
      title: "Vanda — The Outsider",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/vanda-the-outsider.webp",
      width: 1600,
      height: 900,
      alt: "Vanda — The Outsider",
      featured: false,
      sortOrder: 37,
    },
    {
      id: "illustration-best-works-weathergirl-38",
      title: "Weather Girl",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/weathergirl.webp",
      width: 1600,
      height: 900,
      alt: "Weather Girl",
      featured: false,
      sortOrder: 38,
    },
    {
      id: "illustration-best-works-we-chilling-39",
      title: "We Chilling",
      tags: ["Illustration"],
      discipline: "illustration",
      group: "best-works",
      medium: "image",
      image: "/portfolio/illustrations/we-chilling.webp",
      width: 1081,
      height: 1600,
      alt: "We Chilling",
      featured: false,
      sortOrder: 39,
    },
    {
      id: "video-videos-6wc2-india-roster-40",
      title: "6WC2 Team India Roster Reveal",
      tags: ["Video"],
      discipline: "video",
      group: "videos",
      medium: "video",
      image: "/portfolio/video/6wc2-india-roster.webp",
      width: 1280,
      height: 720,
      alt: "6WC2 Team India Roster Reveal",
      embedUrl: "https://youtu.be/ZR870PnoLyE",
      featured: false,
      sortOrder: 40,
    },
    {
      id: "video-videos-6wc3-india-roster-41",
      title: "6WC3 Team India Roster Reveal",
      tags: ["Video"],
      discipline: "video",
      group: "videos",
      medium: "video",
      image: "/portfolio/video/6wc3-india-roster.webp",
      width: 1280,
      height: 720,
      alt: "6WC3 Team India Roster Reveal",
      embedUrl: "https://youtu.be/g2DKg2qC8us",
      featured: false,
      sortOrder: 41,
    },
    {
      id: "video-videos-owc-2024-india-roster-42",
      title: "OWC 2024 Team India Roster Reveal",
      tags: ["Video"],
      discipline: "video",
      group: "videos",
      medium: "video",
      image: "/portfolio/video/owc-2024-india-roster.webp",
      width: 1280,
      height: 720,
      alt: "OWC 2024 Team India Roster Reveal",
      embedUrl: "https://youtu.be/E6CpSOJP_Yw",
      featured: false,
      sortOrder: 42,
    },
    {
      id: "video-videos-jp-top15-2023-43",
      title: "2023 Japanese Top 15 osu!standard Players",
      tags: ["Video"],
      discipline: "video",
      group: "videos",
      medium: "video",
      image: "/portfolio/video/jp-top15-2023.webp",
      width: 1280,
      height: 720,
      alt: "2023 Japanese Top 15 osu!standard Players",
      embedUrl: "https://youtu.be/76MkaIMJJc4",
      featured: false,
      sortOrder: 43,
    },
    {
      id: "video-storyboards-vandalism-the-outsider-44",
      artist: "Ashrount",
      title: "Vandalism -The Outsider- (collab with rrex)",
      tags: ["osu! storyboard"],
      discipline: "video",
      group: "storyboards",
      medium: "storyboard",
      image: "/portfolio/storyboards/vandalism-the-outsider.webp",
      width: 1280,
      height: 720,
      alt: "Vandalism -The Outsider- (collab with rrex)",
      embedUrl: "https://youtu.be/9r3qYjaiZOs",
      featured: false,
      sortOrder: 44,
    },
    {
      id: "video-storyboards-know-me-45",
      artist: "Kairi Yagi",
      title: "know me...",
      tags: ["osu! storyboard"],
      discipline: "video",
      group: "storyboards",
      medium: "storyboard",
      image: "/portfolio/storyboards/know-me.webp",
      width: 1280,
      height: 720,
      alt: "know me...",
      embedUrl: "https://youtu.be/VRVI9Kak8n0",
      featured: false,
      sortOrder: 45,
    },
    {
      id: "video-storyboards-resplendence-46",
      artist: "Kagetora.",
      title: "Resplendence (collab with rrex)",
      tags: ["osu! storyboard"],
      discipline: "video",
      group: "storyboards",
      medium: "storyboard",
      image: "/portfolio/storyboards/resplendence.webp",
      width: 1280,
      height: 720,
      alt: "Resplendence (collab with rrex)",
      embedUrl: "https://youtu.be/lIwasyrpw6w",
      featured: false,
      sortOrder: 46,
    },
    {
      id: "video-storyboards-gumbarlzo-47",
      artist: "t+pazolite",
      title: "Gumbarlzo! (collab with Kuroise)",
      tags: ["osu! storyboard"],
      discipline: "video",
      group: "storyboards",
      medium: "storyboard",
      image: "/portfolio/storyboards/gumbarlzo.webp",
      width: 1280,
      height: 720,
      alt: "Gumbarlzo! (collab with Kuroise)",
      embedUrl: "https://youtu.be/esGtekfbdBg",
      featured: true,
      sortOrder: 47,
    },
    {
      id: "video-storyboards-vividvelocity-48",
      artist: "Synthion",
      title: "VIVIDVELOCITY (collab with -Furimuu)",
      tags: ["osu! storyboard"],
      discipline: "video",
      group: "storyboards",
      medium: "storyboard",
      image: "/portfolio/storyboards/vividvelocity.webp",
      width: 1280,
      height: 720,
      alt: "VIVIDVELOCITY (collab with -Furimuu)",
      embedUrl: "https://youtu.be/E22JPjslChA",
      featured: false,
      sortOrder: 48,
    },
    {
      id: "video-storyboards-scattered-and-lost-49",
      artist: "Lena Raine",
      title: "Scattered and Lost (collab with Coppertine)",
      tags: ["osu! storyboard"],
      discipline: "video",
      group: "storyboards",
      medium: "storyboard",
      image: "/portfolio/storyboards/scattered-and-lost.webp",
      width: 1280,
      height: 720,
      alt: "Scattered and Lost (collab with Coppertine)",
      embedUrl: "https://youtu.be/9yM380VZeQE",
      featured: false,
      sortOrder: 49,
    },
    {
      id: "video-storyboards-nasu-is-not-fruits-desu-50",
      artist: "YUC'e",
      title: "Nasu is Not Fruits Desu!",
      tags: ["osu! storyboard"],
      discipline: "video",
      group: "storyboards",
      medium: "storyboard",
      image: "/portfolio/storyboards/nasu-is-not-fruits-desu.webp",
      width: 1280,
      height: 720,
      alt: "Nasu is Not Fruits Desu!",
      embedUrl: "https://youtu.be/FUEavFSonOU",
      featured: true,
      sortOrder: 50,
    },
  ],

  commissions: {
    section: { title: "commissions" },
    isOpen: false,
    heading: "whoops, commissions are currently closed!",
    body: [
      "I'm currently not accepting any new commissions. I will be taking the time to finish my current commissions and personal projects, and job seeking.",
      "Please contact me to know when I reopen commissions!",
    ],
    image: "/peeking.webp",
    imageAlt: "",
    tiers: [],
  },

  contact: {
    section: { title: "Contact Me!" },
    methods: [
      {
        id: "discord",
        kind: "discord",
        label: "Discord",
        value: "raybeanosu",
        icon: "discord",
        color: "#5865F2",
      },
      {
        id: "email-osu",
        kind: "email",
        label: "Email",
        note: "for osu! enquiries only",
        value: "raybeanosutourney@gmail.com",
        href: "mailto:raybeanosutourney@gmail.com",
        icon: "EnvelopeSimple",
        color: "#C08A2E",
      },
      {
        id: "email-general",
        kind: "email",
        label: "Email",
        note: "for non-osu! enquiries",
        value: "hireraybean@gmail.com",
        href: "mailto:hireraybean@gmail.com",
        icon: "EnvelopeSimple",
        color: "#C08A2E",
      },
    ],
    // form is intentionally absent — it belongs to the message-bot phase.
  },

  footer: {
    copyright: "© {year} Raybean. All rights reserved.",
    tagline: "Made with love and insanity.",
    credit: {
      prefix: "Website by",
      name: "Azaken1248",
      // NEEDS-REAL-VALUE: confirm where this should link.
      href: "https://github.com/Azaken1248",
    },
  },
}
